services:
  frontend:
    image: node:20-alpine
    container_name: frontend
    working_dir: /app
    volumes:
      - ../frontend:/app
    command: sh -c "npm install -g http-server && http-server -p 3000"
    ports:
      - "3000:3000"
